Patch by Ian D. Allen to handle rare case when a service name appears several times in rc3.d (bug 12856)
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/rpm/rpm-helper/trunk@15878 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/add-service b/add-service
--- a/add-service
+++ b/add-service
@@ -71,10 +71,14 @@ else
 
     # if the service is activated, add it again to be able to handle
     # changes in start/stop levels
-    if [ -f /etc/rc3.d/S??$srv ]; then
+    set -- /etc/rc3.d/S??$srv
+    if [ $# -gt 1 ]; then
+	echo 1>&2 "add-service: Error: $srv appears multiple times: $*"
+    fi
+    if [ -f "$1" ]; then
 	/sbin/chkconfig --add $srv
     fi
-    
+
     # restart the service if already running
     if [ -f /var/lock/subsys/$srv ]; then
 	/sbin/service $srv restart > /dev/null 2>/dev/null || :
